### PR TITLE
Try to correct chicken-or-egg problem with users and DB properties

### LINKED ISSUE #125: Chicken Egg problem with users and databases
In the beginning of this role, the databases have been created first and the users after. This allowed to use the `db` setting on the `postgresql_users`. Since https://github.com/geerlingguy/ansible-role-postgresql/commit/929fe7ed3c1920d7278ab9b57fc6a59d31e58166#diff-2444ad0870f91f17ca6c2a5e96b26823 this has been changed, such that the users are created first and the databases second. This allows to set the `owner` on `postgresql_databases` but now the `db` on `postgresql_users` is no longer working.

I guess the only way to fix this is to first create the users and the databases and apply the `db` setting for the `postgresql_users` in a second step, when all databases have been created.

### PR DESCRIPTION
**Pull request by kgizdov**
As the title says. Attempts to fix #125

### CODE REVIEW

**Comment by kgizdov** [comment]
@geerlingguy this CentOS 8 issue seems to be unrelated to my change - could we rerun the CI?

**Comment by breml** [comment]
@geerlingguy Do you mind to have a look at this PR before the stale bot will close this.

**Comment by Migsi** [comment]
Any news on this? I'm still using this role directly pulled from github with this patch applied to fulfill our needs, but I'd love to switch back to the official ansible galaxy version. @geerlingguy any intentions to merge this?

**Comment by geerlingguy** [comment]
No matter what, this would need rebasing as the project now uses GitHub Actions for CI.

**Comment by Migsi** [comment]
> No matter what, this would need rebasing as the project now uses GitHub Actions for CI.

Can I help performing the rebase? In case @kgizdov does not react, I could replicate the patch and submit a PR myself.

**Comment by kgizdov** [comment]
I will rebase on Mon ;)

**Comment by kgizdov** [comment]
@geerlingguy rebased

**Pull request merged**
