### PR TITLE
fix overwritting config options with common prefix

### PR DESCRIPTION
**Pull request by Incanus3**
updated regexp for lineinfile postgresql.conf to match the whole option name before `=` sign

### CODE REVIEW

**Comment by Incanus3** [comment]
hi. is there any plan to merge this?

**Comment by JuddTracy-DAS** [comment]
I have verified this PR works for my systems and should be merged.

**Comment by gaima8** [comment]
The following update to the molecule test verifies there is a problem and that the work @Incanus3 did fixes it.

```
diff --git a/molecule/default/converge.yml b/molecule/default/converge.yml
index bac2eb9..22893c1 100644
--- a/molecule/default/converge.yml
+++ b/molecule/default/converge.yml
@@ -8,6 +8,11 @@
       - name: example
     postgresql_users:
       - name: jdoe
+    postgresql_global_config_options:
+      - option: hot_standby
+        value: 'on'
+      - option: hot_standby_feedback
+        value: 'on'
 
   pre_tasks:
     # The Fedora 30+ container images have only C.UTF-8 installed
```

**Comment by twoequaldots** [comment]
+1.  This PR allowed me to set the correct config (e.g. `pg_stat_statements.*` and `log_*`) I was trying to achieve when using this role.  I've tested in Ansible 2.9.x and will try with 2.10.x tomorrow if it helps.

**Comment by gaima8** [comment]
Not stale. Still a real problem with a real solution.

**Comment by fcecagno** [comment]
Come on, guys! :pray:

**Comment by fcecagno** [comment]
Fixes #158

**Comment by gaima8** [comment]
Still not stale. Still a real problem.

**Pull request closed without merging**
