### PR TITLE
create users before database

### PR DESCRIPTION
**Pull request by daniel-wind**
So that the owner option can be used on de database playbook

### CODE REVIEW

**Comment by UmanShahzad** [comment]
:+1: @geerlingguy I find this useful.

**Comment by geerlingguy** [comment]
So... with the way the Ansible postgres modules work, you can go either way:

  1. Create databases first, then create users who have access to those databases. (This is how Drupal VM currently does it using this role: https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L200-L208).
  2. Create users first, then create databases, with `owner`s.

I'm trying to see what the consensus is, overall... if I swap the order here, it breaks backwards compatibility, and anyone currently using the role would need to rework their databases and users configuration, so it's not a decision I want to make lightly.

**Comment by asharpe** [comment]
The application I'm deploying expects the database to be owned by the user, and that can be made to work (from a playbook) with

```
  roles:
    # must create postgres roles before the database if we want the
    # database owned by a role we create
    - role: postgresql
      vars:
        postgresql_hba_entries: false
        postgresql_users:
          - name: "{{ db.user }}"
            password: "{{ db.user_pass }}"
          - name: "{{ db.other_user }}"
            password: "{{ db.other_user_pass }}"
        postgresql_databases: []
      tags: postgresql

    - role: postgresql
      vars:
        postgresql_hba_entries: false
        postgresql_databases:
          - name: "{{ db.name }}"
            owner: "{{ db.user }}"
      tags: postgresql
```

Another alternative that would support backwards compatibility is to add an "owner" flag to the user, and use "alter database _ owner to _" to make them the owner instead of just granting them permissions.

Using the drupal example (and assuming it wanted ownership, not just permissions), the config would look like

```
# PostgreSQL databases and users.
postgresql_databases:
  - name: "{{ drupal_db_name }}"

postgresql_users:
  - name: "{{ drupal_db_user }}"
    password: "{{ drupal_db_password }}"
    db: "{{ drupal_db_name }}"
    priv: "ALL"
    db_owner: true
```

**Comment by asharpe** [comment]
Yet another option would be to break out permissions into its own task, so that the order of operations is

1. create users
1. create databases
1. create permissions

This might be a bit more work as you'd have to look through the user configs to see what permissions to give them to what databases (backwards compat), however it would be more flexible overall if you could specify permissions as a top level concept (as a sibling to databases and users)

**Comment by towo** [comment]
Bump up the major version when updating so people will look at what's changing in a breakable way (hello, semantic versioning).

Personally, I'm not a fan of explicitly working around race conditions with double include roles and whatnot, so there's two solutions to support that approach

1. Deprecate one of the ownership relations; there's good arguments for either of them to be kept.
2. What @asharpe said. Reuse the `postgresql_users` and `postgresql_databases` variables for a two-pass approach of creating all objects first and permissions last.

**Comment by spruce** [comment]
I, for one, favor the option to have the user also be the owner of the newly created db and not only have permissions on this db.

**Comment by geerlingguy** [comment]
After getting a lot more reports of this, I think I'm okay with switching the behavior—can you please rebase this PR and update it, and I'll create a new major version of the galaxy role so anyone using the current behavior can invert it?

**Comment by daniel-wind** [comment]
Thanks, just updated the PR with the import_tasks behavior and the users first order.

**Comment by dralley** [comment]
Adding another +1 to please do this

**Comment by asmacdo** [comment]
Glad to see this moving forward, it will be very helpful to us!

**Comment by asmacdo** [comment]
@geerlingguy, since this change will create a new major version, etc, are there any other changes that need to happen before this one can get merged? Do you need any help?

I'm asking because our installer is partially broken without this change and I'm trying to determine whether my project should wait on this change or carry a fork until this is released.

**Comment by dralley** [comment]
We're also blocked on https://github.com/geerlingguy/ansible-role-postgresql/pull/53 and https://github.com/geerlingguy/ansible-role-postgresql/pull/54

**Comment by Matt-Yorkley** [comment]
+1 Yes please! I can't deploy my app with the current configuration.

**Comment by marthydavid** [comment]
+ 1

**Comment by weeheavy** [comment]
What is blocking the merge of that pull request exactly? I am also affected by this issue.

**Comment by fmalengreau** [comment]
We also have the problem while installing an openproject server. 
When will it be merged?
Thanks

**Comment by CaeirOps** [comment]
up!

Same issue here, I needed change the task's order to create user before databases.

**Comment by lhoss** [comment]
> After getting a lot more reports of this, I think I'm okay with switching the behavior...

@geerlingguy can you merge this PR/change ?  
( btw great you merged #86 👍 )

**Comment by geerlingguy** [comment]
I'm planning on it before AnsibleFest next week... even sooner if possible.

**Pull request merged**
