### PR TITLE
Add vars file for Ubuntu-24

### PR DESCRIPTION
**Pull request by fapdash**
Tested it on a server and could log into postgres user and start psql.

### CODE REVIEW

**Review by dadangnh — APPROVED** [review]
Tested and works

**Comment by vogella** [comment]
Would be nice to have that in.

**Comment by xorel** [comment]
Would also appreciate this.

**Comment by vogella** [comment]
Workaround, until this is merged:

Create file in ~/.ansible/roles/geerlingguy.postgresql/vars

@geerlingguy any concerns with the PR? If not, please merge so that the next long term support release of Ubuntu is also supported by your playbook.

**Comment by geerlingguy** [comment]
Nope! Just missed it in my scanning of new PRs. Merged and will tag a new release now!

**Comment by vogella** [comment]
Thanks @geerlingguy 

I felt bad for the ping, good that it turned out well.

**Comment by geerlingguy** [comment]
@vogella - Honestly for simpler things like this, I'm always happy to get a ping. I try to catch these when they first come across, but with my notification volume I often miss them now :(

**Pull request merged**
