### PR TITLE
add CentOS-8/RedHat-8 support

### PR DESCRIPTION
**Pull request by anxstj**
This adds support for Centos 8. Please consider integrating this.

### CODE REVIEW

**Comment by lerminou** [comment]
+1 please

**Comment by geerlingguy** [comment]
Happy to merge, but two questions:

1. Can you fix the merge conflict?
2. Can you add `centos8` to the list of tested distros in the `.travis.yml` file?

**Comment by anxstj** [comment]
Looks like this PR needs https://github.com/geerlingguy/ansible-role-postgresql/pull/109 applied first to fix the travis checks.

**Comment by geerlingguy** [comment]
@anxstj - Thanks for pointing that out. I merged that PR, and made a couple small tweaks, and I _think_ it should be ready. One more request: can you add '8' to the EL supported versions in `meta/main.yml`?

**Comment by anxstj** [comment]
@geerlingguy PR should be ready now.

**Pull request merged**
