### PR TITLE
Add support for debian 10

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by mdellweg** [comment]
I guess in the tests, there is no such image for debian10 available yet.

**Comment by geerlingguy** [comment]
@mdellweg - Funny you mention that, I _just_ added a Debian 10 Buster docker/ansible test image today, completely unrelated! https://cloud.docker.com/repository/docker/geerlingguy/docker-debian10-ansible

**Comment by mdellweg** [comment]
@geerlingguy I'm sorry, with this release-detection mechanism, those parameters are searched for in the strangest places.

**Comment by mmoscher** [comment]
Hi @geerlingguy,
can this PR be merged? I'm currently testing our ansible scripts on Debian 10 & would benefit from it.

Thanks in advance :v:

**Comment by geerlingguy** [comment]
Done!

**Comment by mmoscher** [comment]
Great - kudos to both of you :)

**Pull request merged**
