### PR TITLE
Add Fedora support

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by geerlingguy** [comment]
@ehelms - Can you also add `fedora29` to the OS distros tested in the `.travis.yml` config, and make sure it's listed in `meta/main.yml` as one of the supported OSes?

**Comment by ehelms** [comment]
Updated as requested

**Comment by ehelms** [comment]
@geerlingguy please take a look when you can

**Comment by dralley** [comment]
@geerlingguy I would also like this to be merged when possible.  @ehelms there's unfortunately now a merge conflict

**Comment by geerlingguy** [comment]
Moving final work into https://github.com/geerlingguy/ansible-role-postgresql/pull/86 (which has most of these changes, plus Fedora 30). Can you reopen with final changes requested, or collarborate with @mikedep333 on getting the rest of the changes finished?

**Pull request closed without merging**
