### PR TITLE
Add Postgres SCL support on RedHat

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
This requires https://github.com/geerlingguy/ansible-role-postgresql/pull/53 first

**Comment by lhoss** [comment]
Nice PR, which already implemented the redhat (`rh-postgresql96`) SCL I also need 👍 
Only minor 'lint' issues, that I already fixed in my fork, see https://github.com/scigility/ansible-role-postgresql/pull/1
@ehelms You want to cherry-pick my fixes from my PR (or can you first rebase your branch to latest master, then I can easily change my PR to your fork!) ?
Else I can directly create an updated PR to @geerlingguy 's repo (with fixed build), unless he's completely against adding SCL support

ps: Good to understand the reason to use the *syspaths packages (which btw recursively add package `rh-postgresql96-postgresql`), explained in:
https://centos.pkgs.org/7/centos-sclo-rh-testing-x86_64/rh-postgresql96-postgresql-server-syspaths-9.6.5-1.el7.x86_64.rpm.html
> Using the rh-postgresql96-postgresql-server-syspaths package does not require running the 'scl enable' command.
> This package practically replaces the system default postgresql-server package.

p.eg for 9.6
```
__postgresql_packages:
  - rh-postgresql96-postgresql-syspaths
  - rh-postgresql96-postgresql-server-syspaths
  - rh-postgresql96-postgresql-contrib-syspaths
  - rh-postgresql96-postgresql-libs
```

**Comment by lhoss** [comment]
@ehelms can you  rebase / fix conflicts, since #86 was finally merged last hour ?!
Else (I could do it) we need to open new PR!

Worth asking @geerlingguy if he would accept the (fixed) PR !?

**Comment by lhoss** [comment]
I got it working locally (rebased on latest master), so I thought it worth to open a new PR with the done work: https://github.com/geerlingguy/ansible-role-postgresql/pull/96

**Pull request closed without merging**
